name: Update Docker Hub README

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  push-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push README to Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: faircomteam/edge
          readme-filepath: ./README.md
